<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        foreach ($this->data() as $item)
        {
            Country::create($item);
        }
    }
    public function data(): array
    {
        return array(
            array("code"=>"KH","name"=>json_decode('{"en":"Cambodia","fr":"Cambodge"}',true)),
            array("code"=>"CH","name"=>json_decode('{"en":"Switzerland","fr":"Suisse"}',true)),
            array("code"=>"NG","name"=>json_decode('{"en":"Nigeria","fr":"Nigéria"}',true)),
            array("code"=>"CZ","name"=>json_decode('{"en":"Czech Republic","fr":"République tchèque"}',true)),
            array("code"=>"UZ","name"=>json_decode('{"en":"Uzbekistan","fr":"Ouzbékistan"}',true)),
            array("code"=>"GF","name"=>json_decode('{"en":"French Guiana","fr":"Guyane française"}',true)),
            array("code"=>"DE","name"=>json_decode('{"en":"Germany","fr":"Allemagne"}',true)),
            array("code"=>"BH","name"=>json_decode('{"en":"Bahrain","fr":"Bahreïn"}',true)),
            array("code"=>"MH","name"=>json_decode('{"en":"Marshall Islands","fr":"Iles Marshall"}',true)),
            array("code"=>"VE","name"=>json_decode('{"en":"Venezuela","fr":"Venezuela"}',true)),
            array("code"=>"RE","name"=>json_decode('{"en":"Réunion","fr":"Réunion"}',true)),
            array("code"=>"GY","name"=>json_decode('{"en":"Guyana","fr":"Guyana"}',true)),
            array("code"=>"BI","name"=>json_decode('{"en":"Burundi","fr":"Burundi"}',true)),
            array("code"=>"KI","name"=>json_decode('{"en":"Kiribati","fr":"Kiribati"}',true)),
            array("code"=>"JO","name"=>json_decode('{"en":"Jordan","fr":"Jordanie"}',true)),
            array("code"=>"AU","name"=>json_decode('{"en":"Australia","fr":"Australie"}',true)),
            array("code"=>"EH","name"=>json_decode('{"en":"Western Sahara","fr":"Sahara occidental"}',true)),
            array("code"=>"GE","name"=>json_decode('{"en":"Georgia","fr":"Géorgie"}',true)),
            array("code"=>"LU","name"=>json_decode('{"en":"Luxembourg","fr":"Luxembourg"}',true)),
            array("code"=>"JP","name"=>json_decode('{"en":"Japan","fr":"Japon"}',true)),
            array("code"=>"BO","name"=>json_decode('{"en":"Bolivia","fr":"Bolivie"}',true)),
            array("code"=>"AL","name"=>json_decode('{"en":"Albania","fr":"Albanie"}',true)),
            array("code"=>"ME","name"=>json_decode('{"en":"Montenegro","fr":"Monténégro"}',true)),
            array("code"=>"US","name"=>json_decode('{"en":"United States","fr":"Etats-Unis"}',true)),
            array("code"=>"BA","name"=>json_decode('{"en":"Bosnia and Herzegovina","fr":"Bosnie-Herzégovine"}',true)),
            array("code"=>"PG","name"=>json_decode('{"en":"Papua New Guinea","fr":"Papouasie-Nouvelle-Guinée"}',true)),
            array("code"=>"LV","name"=>json_decode('{"en":"Latvia","fr":"Lettonie"}',true)),
            array("code"=>"IR","name"=>json_decode('{"en":"Iran","fr":"Iran"}',true)),
            array("code"=>"GM","name"=>json_decode('{"en":"Gambia","fr":"Gambie"}',true)),
            array("code"=>"NC","name"=>json_decode('{"en":"New Caledonia","fr":"Nouvelle-Calédonie"}',true)),
            array("code"=>"KS","name"=>json_decode('{"en":"Kosovo","fr":"Kosovo"}',true)),
            array("code"=>"BN","name"=>json_decode('{"en":"Brunei Darussalam","fr":"Brunéi Darussalam"}',true)),
            array("code"=>"BR","name"=>json_decode('{"en":"Brazil","fr":"Brésil"}',true)),
            array("code"=>"NO","name"=>json_decode('{"en":"Norway","fr":"Norvège"}',true)),
            array("code"=>"GA","name"=>json_decode('{"en":"Gabon","fr":"Gabon"}',true)),
            array("code"=>"T2","name"=>json_decode('{"en":"Tanzania (Zanzibar),","fr":"Tanzanie (Zanzibar)"}',true)),
            array("code"=>"IQ","name"=>json_decode('{"en":"Iraq","fr":"Iraq"}',true)),
            array("code"=>"DJ","name"=>json_decode('{"en":"Djibouti","fr":"Djibouti"}',true)),
            array("code"=>"PL","name"=>json_decode('{"en":"Poland","fr":"Pologne"}',true)),
            array("code"=>"SO","name"=>json_decode('{"en":"Somalia","fr":"Somalie"}',true)),
            array("code"=>"GI","name"=>json_decode('{"en":"Gibraltar","fr":"Gibraltar"}',true)),
            array("code"=>"TW","name"=>json_decode('{"en":"Taiwan, China","fr":"Taïwan, Chine"}',true)),
            array("code"=>"CD","name"=>json_decode('{"en":"Congo, Democratic Republic of the","fr":"Congo, Rép. dém. du"}',true)),
            array("code"=>"MP","name"=>json_decode('{"en":"Northern Mariana Islands","fr":"Iles Mariannes du Nord"}',true)),
            array("code"=>"ET","name"=>json_decode('{"en":"Ethiopia","fr":"Ethiopie"}',true)),
            array("code"=>"AT","name"=>json_decode('{"en":"Austria","fr":"Autriche"}',true)),
            array("code"=>"CN","name"=>json_decode('{"en":"China","fr":"Chine"}',true)),
            array("code"=>"SN","name"=>json_decode('{"en":"Senegal","fr":"Sénégal"}',true)),
            array("code"=>"NF","name"=>json_decode('{"en":"Norfolk Island","fr":"Ile Norfolk"}',true)),
            array("code"=>"KN","name"=>json_decode('{"en":"Saint Kitts and Nevis","fr":"Saint-Kitts-et-Nevis"}',true)),
            array("code"=>"BT","name"=>json_decode('{"en":"Bhutan","fr":"Bhoutan"}',true)),
            array("code"=>"PW","name"=>json_decode('{"en":"Palau","fr":"Palau"}',true)),
            array("code"=>"KZ","name"=>json_decode('{"en":"Kazakhstan","fr":"Kazakhstan"}',true)),
            array("code"=>"BJ","name"=>json_decode('{"en":"Benin","fr":"Bénin"}',true)),
            array("code"=>"AW","name"=>json_decode('{"en":"Aruba","fr":"Aruba"}',true)),
            array("code"=>"CS","name"=>json_decode('{"en":"Serbia and Montenegro","fr":"Serbie-et-Monténégro"}',true)),
            array("code"=>"DO","name"=>json_decode('{"en":"Dominican Republic","fr":"République dominicaine"}',true)),
            array("code"=>"Y1","name"=>json_decode('{"en":"Yemen, The former Arab Rep. of","fr":"Yémen, Ancienne Rép. arabe du"}',true)),
            array("code"=>"NL","name"=>json_decode('{"en":"Netherlands","fr":"Pays-Bas"}',true)),
            array("code"=>"TN","name"=>json_decode('{"en":"Tunisia","fr":"Tunisie"}',true)),
            array("code"=>"CY","name"=>json_decode('{"en":"Cyprus","fr":"Chypre"}',true)),
            array("code"=>"M3","name"=>json_decode('{"en":"Malaysia: Sarawak","fr":"Malaisie: Sarawak"}',true)),
            array("code"=>"KP","name"=>json_decode('{"en":"Korea","fr":"Corée"}',true)),
            array("code"=>"LB","name"=>json_decode('{"en":"Lebanon","fr":"Liban"}',true)),
            array("code"=>"LR","name"=>json_decode('{"en":"Liberia","fr":"Libéria"}',true)),
            array("code"=>"AZ","name"=>json_decode('{"en":"Azerbaijan","fr":"Azerbaïdjan"}',true)),
            array("code"=>"ES","name"=>json_decode('{"en":"Spain","fr":"Espagne"}',true)),
            array("code"=>"QA","name"=>json_decode('{"en":"Qatar","fr":"Qatar"}',true)),
            array("code"=>"OM","name"=>json_decode('{"en":"Oman","fr":"Oman"}',true)),
            array("code"=>"SK","name"=>json_decode('{"en":"Slovakia","fr":"Slovaquie"}',true)),
            array("code"=>"CV","name"=>json_decode('{"en":"Cape Verde","fr":"Cap-Vert"}',true)),
            array("code"=>"GB","name"=>json_decode('{"en":"United Kingdom","fr":"Royaume-Uni"}',true)),
            array("code"=>"MT","name"=>json_decode('{"en":"Malta","fr":"Malte"}',true)),
            array("code"=>"IL","name"=>json_decode('{"en":"Israel","fr":"Israël"}',true)),
            array("code"=>"LS","name"=>json_decode('{"en":"Lesotho","fr":"Lesotho"}',true)),
            array("code"=>"LA","name"=>json_decode('{"en":"Lao People\'s Dem. Rep.","fr":"République dém. pop. lao"}',true)),
            array("code"=>"BF","name"=>json_decode('{"en":"Burkina Faso","fr":"Burkina Faso"}',true)),
            array("code"=>"VC","name"=>json_decode('{"en":"Saint Vincent and the Grenadines","fr":"Saint-Vincent-et-les Grenadines"}',true)),
            array("code"=>"PM","name"=>json_decode('{"en":"Saint Pierre and Miquelon","fr":"Saint-Pierre-et-Miquelon"}',true)),
            array("code"=>"SI","name"=>json_decode('{"en":"Slovenia","fr":"Slovénie"}',true)),
            array("code"=>"BB","name"=>json_decode('{"en":"Barbados","fr":"Barbade"}',true)),
            array("code"=>"IE","name"=>json_decode('{"en":"Ireland","fr":"Irlande"}',true)),
            array("code"=>"CI","name"=>json_decode('{"en":"Côte d\'Ivoire","fr":"Côte d\'Ivoire"}',true)),
            array("code"=>"RW","name"=>json_decode('{"en":"Rwanda","fr":"Rwanda"}',true)),
            array("code"=>"TV","name"=>json_decode('{"en":"Tuvalu","fr":"Tuvalu"}',true)),
            array("code"=>"SM","name"=>json_decode('{"en":"San Marino","fr":"Saint-Marin"}',true)),
            array("code"=>"ER","name"=>json_decode('{"en":"Eritrea","fr":"Erythrée"}',true)),
            array("code"=>"GL","name"=>json_decode('{"en":"Greenland","fr":"Groenland"}',true)),
            array("code"=>"TM","name"=>json_decode('{"en":"Turkmenistan","fr":"Turkménistan"}',true)),
            array("code"=>"KE","name"=>json_decode('{"en":"Kenya","fr":"Kenya"}',true)),
            array("code"=>"TJ","name"=>json_decode('{"en":"Tajikistan","fr":"Tadjikistan"}',true)),
            array("code"=>"AI","name"=>json_decode('{"en":"Anguilla","fr":"Anguilla"}',true)),
            array("code"=>"FO","name"=>json_decode('{"en":"Faeroe Islands","fr":"Iles Féroé"}',true)),
            array("code"=>"MG","name"=>json_decode('{"en":"Madagascar","fr":"Madagascar"}',true)),
            array("code"=>"LI","name"=>json_decode('{"en":"Liechtenstein","fr":"Liechtenstein"}',true)),
            array("code"=>"SZ","name"=>json_decode('{"en":"Swaziland","fr":"Swaziland"}',true)),
            array("code"=>"WF","name"=>json_decode('{"en":"Wallis and Futuna Islands","fr":"Iles Wallis et Futuna"}',true)),
            array("code"=>"TH","name"=>json_decode('{"en":"Thailand","fr":"Thaïlande"}',true)),
            array("code"=>"TL","name"=>json_decode('{"en":"Timor-Leste","fr":"Timor-Leste"}',true)),
            array("code"=>"BE","name"=>json_decode('{"en":"Belgium","fr":"Belgique"}',true)),
            array("code"=>"IS","name"=>json_decode('{"en":"Iceland","fr":"Islande"}',true)),
            array("code"=>"BG","name"=>json_decode('{"en":"Bulgaria","fr":"Bulgarie"}',true)),
            array("code"=>"SS","name"=>json_decode('{"en":"South Sudan","fr":"Soudan du Sud"}',true)),
            array("code"=>"TR","name"=>json_decode('{"en":"Turkey","fr":"Turquie"}',true)),
            array("code"=>"MW","name"=>json_decode('{"en":"Malawi","fr":"Malawi"}',true)),
            array("code"=>"GN","name"=>json_decode('{"en":"Guinea","fr":"Guinée"}',true)),
            array("code"=>"MY","name"=>json_decode('{"en":"Malaysia","fr":"Malaisie"}',true)),
            array("code"=>"SC","name"=>json_decode('{"en":"Seychelles","fr":"Seychelles"}',true)),
            array("code"=>"MO","name"=>json_decode('{"en":"Macau, China","fr":"Macao, Chine"}',true)),
            array("code"=>"UG","name"=>json_decode('{"en":"Uganda","fr":"Ouganda"}',true)),
            array("code"=>"MA","name"=>json_decode('{"en":"Morocco","fr":"Maroc"}',true)),
            array("code"=>"RU","name"=>json_decode('{"en":"Russian","fr":"Russie"}',true)),
            array("code"=>"VG","name"=>json_decode('{"en":"British Virgin Islands","fr":"Iles Vierges britanniques"}',true)),
            array("code"=>"C1","name"=>json_decode('{"en":"Czechoslovakia","fr":"Tchécoslovaquie"}',true)),
            array("code"=>"SB","name"=>json_decode('{"en":"Solomon Islands","fr":"Iles Salomon"}',true)),
            array("code"=>"IN","name"=>json_decode('{"en":"India","fr":"Inde"}',true)),
            array("code"=>"JE","name"=>json_decode('{"en":"Jersey","fr":"Jersey"}',true)),
            array("code"=>"MS","name"=>json_decode('{"en":"Montserrat","fr":"Montserrat"}',true)),
            array("code"=>"MN","name"=>json_decode('{"en":"Mongolia","fr":"Mongolie"}',true)),
            array("code"=>"HU","name"=>json_decode('{"en":"Hungary","fr":"Hongrie"}',true)),
            array("code"=>"ID","name"=>json_decode('{"en":"Indonesia","fr":"Indonésie"}',true)),
            array("code"=>"BM","name"=>json_decode('{"en":"Bermuda","fr":"Bermudes"}',true)),
            array("code"=>"DM","name"=>json_decode('{"en":"Dominica","fr":"Dominique"}',true)),
            array("code"=>"NE","name"=>json_decode('{"en":"Niger","fr":"Niger"}',true)),
            array("code"=>"FJ","name"=>json_decode('{"en":"Fiji","fr":"Fidji"}',true)),
            array("code"=>"CM","name"=>json_decode('{"en":"Cameroon","fr":"Cameroun"}',true)),
            array("code"=>"DK","name"=>json_decode('{"en":"Denmark","fr":"Danemark"}',true)),
            array("code"=>"VU","name"=>json_decode('{"en":"Vanuatu","fr":"Vanuatu"}',true)),
            array("code"=>"ST","name"=>json_decode('{"en":"Sao Tome and Principe","fr":"Sao Tomé-et-Principe"}',true)),
            array("code"=>"TD","name"=>json_decode('{"en":"Chad","fr":"Tchad"}',true)),
            array("code"=>"NZ","name"=>json_decode('{"en":"New Zealand","fr":"Nouvelle-Zélande"}',true)),
            array("code"=>"CA","name"=>json_decode('{"en":"Canada","fr":"Canada"}',true)),
            array("code"=>"KG","name"=>json_decode('{"en":"Kyrgyzstan","fr":"Kirghizistan"}',true)),
            array("code"=>"JG","name"=>json_decode('{"en":"Channel Islands","fr":"Iles Anglo-normandes"}',true)),
            array("code"=>"TT","name"=>json_decode('{"en":"Trinidad and Tobago","fr":"Trinité-et-Tobago"}',true)),
            array("code"=>"GQ","name"=>json_decode('{"en":"Equatorial Guinea","fr":"Guinée équatoriale"}',true)),
            array("code"=>"SR","name"=>json_decode('{"en":"Suriname","fr":"Suriname"}',true)),
            array("code"=>"ZM","name"=>json_decode('{"en":"Zambia","fr":"Zambie"}',true)),
            array("code"=>"AN","name"=>json_decode('{"en":"Netherlands Antilles","fr":"Antilles néerlandaises"}',true)),
            array("code"=>"Y3","name"=>json_decode('{"en":"Yugoslavia, The former Socialist Fed. Rep. of","fr":"Yougoslavie, Ancienne Rép. socialiste de"}',true)),
            array("code"=>"MM","name"=>json_decode('{"en":"Myanmar","fr":"Myanmar"}',true)),
            array("code"=>"GP","name"=>json_decode('{"en":"Guadeloupe","fr":"Guadeloupe"}',true)),
            array("code"=>"MX","name"=>json_decode('{"en":"Mexico","fr":"Mexique"}',true)),
            array("code"=>"MU","name"=>json_decode('{"en":"Mauritius","fr":"Maurice"}',true)),
            array("code"=>"SA","name"=>json_decode('{"en":"Saudi Arabia","fr":"Arabie saoudite"}',true)),
            array("code"=>"LK","name"=>json_decode('{"en":"Sri Lanka","fr":"Sri Lanka"}',true)),
            array("code"=>"NR","name"=>json_decode('{"en":"Nauru","fr":"Nauru"}',true)),
            array("code"=>"MK","name"=>json_decode('{"en":"Macedonia","fr":"Macédoine"}',true)),
            array("code"=>"FK","name"=>json_decode('{"en":"Falkland Islands (Malvinas)","fr":"Iles Falkland (Malvinas)"}',true)),
            array("code"=>"MD","name"=>json_decode('{"en":"Moldova","fr":"Moldavie"}',true)),
            array("code"=>"GT","name"=>json_decode('{"en":"Guatemala","fr":"Guatemala"}',true)),
            array("code"=>"AO","name"=>json_decode('{"en":"Angola","fr":"Angola"}',true)),
            array("code"=>"VN","name"=>json_decode('{"en":"Viet Nam","fr":"Viet Nam"}',true)),
            array("code"=>"RS","name"=>json_decode('{"en":"Serbia","fr":"Serbie"}',true)),
            array("code"=>"KM","name"=>json_decode('{"en":"Comoros","fr":"Comores"}',true)),
            array("code"=>"GH","name"=>json_decode('{"en":"Ghana","fr":"Ghana"}',true)),
            array("code"=>"TZ","name"=>json_decode('{"en":"Tanzania","fr":"Tanzanie"}',true)),
            array("code"=>"MQ","name"=>json_decode('{"en":"Martinique","fr":"Martinique"}',true)),
            array("code"=>"AG","name"=>json_decode('{"en":"Antigua and Barbuda","fr":"Antigua-et-Barbuda"}',true)),
            array("code"=>"AR","name"=>json_decode('{"en":"Argentina","fr":"Argentine"}',true)),
            array("code"=>"RO","name"=>json_decode('{"en":"Romania","fr":"Roumanie"}',true)),
            array("code"=>"PS","name"=>json_decode('{"en":"West Bank and Gaza Strip","fr":"Rive occidentale et Bande de Gaza"}',true)),
            array("code"=>"JM","name"=>json_decode('{"en":"Jamaica","fr":"Jamaïque"}',true)),
            array("code"=>"MV","name"=>json_decode('{"en":"Maldives","fr":"Maldives"}',true)),
            array("code"=>"GW","name"=>json_decode('{"en":"Guinea-Bissau","fr":"Guinée-Bissau"}',true)),
            array("code"=>"MR","name"=>json_decode('{"en":"Mauritania","fr":"Mauritanie"}',true)),
            array("code"=>"BW","name"=>json_decode('{"en":"Botswana","fr":"Botswana"}',true)),
            array("code"=>"TK","name"=>json_decode('{"en":"Tokelau","fr":"Tokélaou"}',true)),
            array("code"=>"HK","name"=>json_decode('{"en":"Hong Kong, China","fr":"Hong-kong, Chine"}',true)),
            array("code"=>"SG","name"=>json_decode('{"en":"Singapore","fr":"Singapour"}',true)),
            array("code"=>"KR","name"=>json_decode('{"en":"Korea","fr":"Corée"}',true)),
            array("code"=>"ML","name"=>json_decode('{"en":"Mali","fr":"Mali"}',true)),
            array("code"=>"AS","name"=>json_decode('{"en":"American Samoa","fr":"Samoa américaines"}',true)),
            array("code"=>"LT","name"=>json_decode('{"en":"Lithuania","fr":"Lituanie"}',true)),
            array("code"=>"ZA","name"=>json_decode('{"en":"South Africa","fr":"Afrique du Sud"}',true)),
            array("code"=>"SH","name"=>json_decode('{"en":"Saint Helena","fr":"Sainte-Hélène"}',true)),
            array("code"=>"NA","name"=>json_decode('{"en":"Namibia","fr":"Namibie"}',true)),
            array("code"=>"AD","name"=>json_decode('{"en":"Andorra","fr":"Andorre"}',true)),
            array("code"=>"NP","name"=>json_decode('{"en":"Nepal","fr":"Népal"}',true)),
            array("code"=>"UY","name"=>json_decode('{"en":"Uruguay","fr":"Uruguay"}',true)),
            array("code"=>"LC","name"=>json_decode('{"en":"Saint Lucia","fr":"Sainte-Lucie"}',true)),
            array("code"=>"PF","name"=>json_decode('{"en":"French Polynesia","fr":"Polynésie française"}',true)),
            array("code"=>"EG","name"=>json_decode('{"en":"Egypt","fr":"Egypte"}',true)),
            array("code"=>"WS","name"=>json_decode('{"en":"Samoa","fr":"Samoa"}',true)),
            array("code"=>"BY","name"=>json_decode('{"en":"Belarus","fr":"Bélarus"}',true)),
            array("code"=>"PA","name"=>json_decode('{"en":"Panama","fr":"Panama"}',true)),
            array("code"=>"HT","name"=>json_decode('{"en":"Haiti","fr":"Haïti"}',true)),
            array("code"=>"BD","name"=>json_decode('{"en":"Bangladesh","fr":"Bangladesh"}',true)),
            array("code"=>"EC","name"=>json_decode('{"en":"Ecuador","fr":"Equateur"}',true)),
            array("code"=>"NI","name"=>json_decode('{"en":"Nicaragua","fr":"Nicaragua"}',true)),
            array("code"=>"CU","name"=>json_decode('{"en":"Cuba","fr":"Cuba"}',true)),
            array("code"=>"KW","name"=>json_decode('{"en":"Kuwait","fr":"Koweït"}',true)),
            array("code"=>"PT","name"=>json_decode('{"en":"Portugal","fr":"Portugal"}',true)),
            array("code"=>"GR","name"=>json_decode('{"en":"Greece","fr":"Grèce"}',true)),
            array("code"=>"YE","name"=>json_decode('{"en":"Yemen","fr":"Yémen"}',true)),
            array("code"=>"M2","name"=>json_decode('{"en":"Malaysia: Sabah","fr":"Malaisie: Sabah"}',true)),
            array("code"=>"IM","name"=>json_decode('{"en":"Isle of Man","fr":"Ile de Man"}',true)),
            array("code"=>"TC","name"=>json_decode('{"en":"Turks and Caicos Islands","fr":"Iles Turques et Caïques"}',true)),
            array("code"=>"LY","name"=>json_decode('{"en":"Libyan Arab Jamahiriya","fr":"Jamahiriya arabe libyenne"}',true)),
            array("code"=>"HR","name"=>json_decode('{"en":"Croatia","fr":"Croatie"}',true)),
            array("code"=>"TG","name"=>json_decode('{"en":"Togo","fr":"Togo"}',true)),
            array("code"=>"CF","name"=>json_decode('{"en":"Central African Republic","fr":"République centrafricaine"}',true)),
            array("code"=>"DZ","name"=>json_decode('{"en":"Algeria","fr":"Algérie"}',true)),
            array("code"=>"GU","name"=>json_decode('{"en":"Guam","fr":"Guam"}',true)),
            array("code"=>"GD","name"=>json_decode('{"en":"Grenada","fr":"Grenade"}',true)),
            array("code"=>"FR","name"=>json_decode('{"en":"France","fr":"France"}',true)),
            array("code"=>"MZ","name"=>json_decode('{"en":"Mozambique","fr":"Mozambique"}',true)),
            array("code"=>"EE","name"=>json_decode('{"en":"Estonia","fr":"Estonie"}',true)),
            array("code"=>"CL","name"=>json_decode('{"en":"Chile","fr":"Chili"}',true)),
            array("code"=>"PR","name"=>json_decode('{"en":"Puerto Rico","fr":"Porto Rico"}',true)),
            array("code"=>"CR","name"=>json_decode('{"en":"Costa Rica","fr":"Costa Rica"}',true)),
            array("code"=>"AM","name"=>json_decode('{"en":"Armenia","fr":"Arménie"}',true)),
            array("code"=>"GG","name"=>json_decode('{"en":"Guernsey","fr":"Guernesey"}',true)),
            array("code"=>"T1","name"=>json_decode('{"en":"Tanzania (Tanganyika)","fr":"Tanzanie (Tanganyika)"}',true)),
            array("code"=>"UA","name"=>json_decode('{"en":"Ukraine","fr":"Ukraine"}',true)),
            array("code"=>"ZW","name"=>json_decode('{"en":"Zimbabwe","fr":"Zimbabwe"}',true)),
            array("code"=>"SY","name"=>json_decode('{"en":"Syrian Arab Republic","fr":"République arabe syrienne"}',true)),
            array("code"=>"TO","name"=>json_decode('{"en":"Tonga","fr":"Tonga"}',true)),
            array("code"=>"SD","name"=>json_decode('{"en":"Sudan","fr":"Soudan"}',true)),
            array("code"=>"NU","name"=>json_decode('{"en":"Niue","fr":"Nioué"}',true)),
            array("code"=>"BZ","name"=>json_decode('{"en":"Belize","fr":"Belize"}',true)),
            array("code"=>"IT","name"=>json_decode('{"en":"Italy","fr":"Italie"}',true)),
            array("code"=>"FI","name"=>json_decode('{"en":"Finland","fr":"Finlande"}',true)),
            array("code"=>"PY","name"=>json_decode('{"en":"Paraguay","fr":"Paraguay"}',true)),
            array("code"=>"AF","name"=>json_decode('{"en":"Afghanistan","fr":"Afghanistan"}',true)),
            array("code"=>"AE","name"=>json_decode('{"en":"United Arab Emirates","fr":"Emirats arabes unis"}',true)),
            array("code"=>"PE","name"=>json_decode('{"en":"Peru","fr":"Pérou"}',true)),
            array("code"=>"CG","name"=>json_decode('{"en":"Congo","fr":"Congo"}',true)),
            array("code"=>"HN","name"=>json_decode('{"en":"Honduras","fr":"Honduras"}',true)),
            array("code"=>"VI","name"=>json_decode('{"en":"Virgin Islands (US),","fr":"Iles Vierges américaines"}',true)),
            array("code"=>"CK","name"=>json_decode('{"en":"Cook Islands","fr":"Iles Cook"}',true)),
            array("code"=>"SL","name"=>json_decode('{"en":"Sierra Leone","fr":"Sierra Leone"}',true)),
            array("code"=>"M1","name"=>json_decode('{"en":"Malaysia: Peninsular Malaysia","fr":"Malaisie: Malaisie péninsulaire"}',true)),
            array("code"=>"SE","name"=>json_decode('{"en":"Sweden","fr":"Suède"}',true)),
            array("code"=>"PK","name"=>json_decode('{"en":"Pakistan","fr":"Pakistan"}',true)),
            array("code"=>"KY","name"=>json_decode('{"en":"Cayman Islands","fr":"Iles Caïmanes"}',true)),
            array("code"=>"MC","name"=>json_decode('{"en":"Monaco","fr":"Monaco"}',true)),
            array("code"=>"BS","name"=>json_decode('{"en":"Bahamas","fr":"Bahamas"}',true)),
            array("code"=>"E1","name"=>json_decode('{"en":"Ethiopia","fr":"Ethiopie"}',true)),
            array("code"=>"CO","name"=>json_decode('{"en":"Colombia","fr":"Colombie"}',true)),
            array("code"=>"SV","name"=>json_decode('{"en":"El Salvador","fr":"El Salvador"}',true)),
            array("code"=>"PH","name"=>json_decode('{"en":"Philippines","fr":"Philippines"}',true)),
        );

    }
}
